'throw keyword' is used to used to create exception ourseleves explicitly
Any statement written after throw becomes unreachable.
